name: better_auth_flutter
description: "A Flutter client package for integrating with Better Auth - a
  secure authentication platform."
version: 0.0.6
homepage: https://www.better-auth.com/
repository: https://github.com/ekakshjanweja/better_auth_flutter
issue_tracker: https://github.com/ekakshjanweja/better_auth_flutter/issues

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  auto_exporter_annotation: 1.0.3
  cookie_jar: ^4.0.8
  flutter:
    sdk: flutter
  flutter_web_auth_2: ^4.1.0
  http: ^1.3.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  auto_exporter: 3.5.1
  build_runner: 2.5.4
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter

platforms:
  android:
  ios:
  macos:
  windows:
  linux:
