name: better_auth_flutter
description: "Flutter Client side SDK for Better Auth"
version: 0.0.1
homepage: https://stormej.me

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  auto_exporter_annotation: ^1.0.2
  flutter:
    sdk: flutter
  google_sign_in: ^6.3.0
  http: ^1.3.0
  shared_preferences: ^2.5.3

dev_dependencies:
  auto_exporter: ^3.4.2
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
