name: better_auth_flutter
description: "Flutter Client side SDK for Better Auth"
version: 0.0.1
homepage: https://stormej.mehttps://github.com/ekakshjanweja/better_auth_flutter
repository: https://github.com/ekakshjanweja/better_auth_flutter
issue_tracker: https://github.com/ekakshjanweja/better_auth_flutter/issues

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  auto_exporter_annotation: ^1.0.2
  cookie_jar: ^4.0.8
  flutter:
    sdk: flutter
  google_sign_in: ^6.3.0
  http: ^1.3.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  auto_exporter: ^3.4.2
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
